# bash_aliases
#
# This file is copied into the home directory of the vagrant user on the virtual
# machine during provisioning and is included in the .bashrc automatically as
# provisioning is finished. This allows for various scripts and configurations to
# be available to us.
#

# If XDebug is enabled, disable it
xdebug_off() {
	sudo php5dismod xdebug
	sudo service php5-fpm restart
}

# If XDebug is disabled, enable it
xdebug_on() {
	sudo php5enmod xdebug
	sudo service php5-fpm restart
}
